# Generated by Django 5.2.4 on 2025-08-23 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_followerscount_timestamp_profile_followers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="no_of_likes",
        ),
    ]
