# Generated by Django 5.2.4 on 2025-08-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics"),
        ),
    ]
